// <auto-generated />
using System;
using GradesService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradesService.Infrastructure.Migrations
{
    [DbContext(typeof(GradesDbContext))]
    [Migration("20251208014034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GradesService.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("GradeCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GradeCategoryId");

                    b.HasIndex("GradeDate");

                    b.HasIndex("StudentId", "SubjectId", "AcademicPeriodId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("GradesService.Domain.Entities.GradeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WeightPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GradeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 8, 1, 40, 33, 80, DateTimeKind.Utc).AddTicks(4017),
                            Description = "Evaluaciones escritas",
                            IsActive = true,
                            Name = "Exámenes",
                            WeightPercentage = 40m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 1, 40, 33, 80, DateTimeKind.Utc).AddTicks(4020),
                            Description = "Trabajos y tareas",
                            IsActive = true,
                            Name = "Tareas",
                            WeightPercentage = 30m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 8, 1, 40, 33, 80, DateTimeKind.Utc).AddTicks(4021),
                            Description = "Participación en clase",
                            IsActive = true,
                            Name = "Participación",
                            WeightPercentage = 20m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 8, 1, 40, 33, 80, DateTimeKind.Utc).AddTicks(4023),
                            Description = "Proyecto final del curso",
                            IsActive = true,
                            Name = "Proyecto Final",
                            WeightPercentage = 10m
                        });
                });

            modelBuilder.Entity("GradesService.Domain.Entities.StudentGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "SubjectId", "AcademicPeriodId")
                        .IsUnique();

                    b.ToTable("StudentGrades");
                });

            modelBuilder.Entity("GradesService.Domain.Entities.Grade", b =>
                {
                    b.HasOne("GradesService.Domain.Entities.GradeCategory", "GradeCategory")
                        .WithMany("Grades")
                        .HasForeignKey("GradeCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GradeCategory");
                });

            modelBuilder.Entity("GradesService.Domain.Entities.GradeCategory", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
